name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image latest
      run: docker build -f Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/demo:latest ./
    - name: Tag image with commit SHA
      run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/demo:latest ${{ vars.DOCKERHUB_USERNAME }}/demo:$GIT_SHA
    - name: Push to Docker Hub latest
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/demo:latest
    - name: Push to Docker Hub commit SHA
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        docker push ${{ vars.DOCKERHUB_USERNAME }}/demo:$GIT_SHA
