name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...     


  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image latest
      run: docker build -f Dockerfile -t ${{ vars.DOCKERHUB_USERNAME }}/demo:latest ./
    - name: Tag image with commit SHA
      run: |
          GIT_SHA=$(git rev-parse --short HEAD)
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/demo:latest ${{ vars.DOCKERHUB_USERNAME }}/demo:$GIT_SHA

    - name: Trivy scan Docker image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{ vars.DOCKERHUB_USERNAME }}/demo:latest'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: '1'

    - name: Trivy scan source code and Dockerfile
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    - name: Push to Docker Hub latest
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/demo:latest
    - name: Push to Docker Hub commit SHA
      run: |
        GIT_SHA=$(git rev-parse --short HEAD)
        docker push ${{ vars.DOCKERHUB_USERNAME }}/demo:$GIT_SHA
